theme: jekyll-theme-minimal
title: Introduction to Bioinformatics Class S18
description: A repository to store and display my work completed during the Spring 2018 quarter in BIMM-143 at UCSD.
logo: https://bioboot.github.io/bimm143_S18/assets/img/logo.png
